### ISSUE TITLE
Supply contracts criteria

### ISSUE THREAD

**Issue by MariaSpr** [UPRC-Interop/espd-vcd-system#19]
Λάθος όνομα κριτηρίου και περιγραφή του κριτηρίου:

"Για τις συμβάσεις προμηθειών: δείγματα, περιγραφή ή φωτογραφίες χωρίς την πιστοποίηση γνησιότητας "

Επιπλέον, το νέο pdf επαναλαμβάνει το 2 φορές το "Για τις συμβάσεις προμηθειών: δείγματα, περιγραφή ή φωτογραφίες με πιστοποίηση γνησιότητας"

![image](https://github.com/user-attachments/assets/1a9320b8-843e-45a9-9826-006d5cbc9cd9)

**Comment by charis-ant** [comment]
The name and the description of the criterion is correct. 
Which of the two  **"Για τις συμβάσεις προμηθειών: δείγματα, περιγραφή ή φωτογραφίες με πιστοποίηση γνησιότητας"** needs to remain?
![image](https://github.com/user-attachments/assets/97159e35-11e1-42f7-ac1e-ed88d3e0de6f)

**Comment by MariaSpr** [comment]
Fixed
Note: QA done on branch pdf-issues commit hash 8b23ef0a
