### ISSUE TITLE
Server config of selected/mandatory criteria

### ISSUE THREAD

**Issue by MariaSpr** [UPRC-Interop/espd-vcd-system#28]
Κάτι πάει λάθος με το config του server το οποίο έφερνε ποια κριτήρια είναι mandatory (άρα selected και grayed out ώστε να μη μπορεί να τα ξε-τσεκάρει ο χρήστης) ή pre-selected (απλά selected αλλά μπορούσες να τα ξετσεκάρεις). 

Υπάρχει ασυμφωνία μεταξύ παραγωγικού και stage environment.

@konstantinosraptis91 και @charis-ant για να το δείτε θα κάνετε το εξής:

Create from scratch **ESPD request** (CA) στο stage: 
Πάτε στα κριτήρια επιλογής στο Γ: Τεχνική και επαγγελματική ικανότητα.
Το κριτήριο "Ποσοστό Υπεργολαβίας" το βγάζει mandatory ενώ στο παραγωγικό δεν είναι
![image](https://github.com/user-attachments/assets/c676aaa3-1452-4e68-8c13-0b78f8c3a06a)

Κάντε το ίδιο και στο παραγωγικό, το συγκεκριμένο κριτήριο δεν είναι mandatory. (και δε πρέπει κιόλας σύμφωνα με το taxonomy)

@konstantinosraptis91 τσέκαρε το config +θυμήσου μήπως το υπουργείο το είχε ζητήσει να γίνει έτσι στα τελευταία tickets που είχαν ζητήσει.

@charis-ant μπορείς να τσεκάρεις και εσύ stage-prod και να συγκρίνεις και εσύ ποια είναι mandatory/pre-selected? Μπορεί να υπάρχει και άλλο τέτοιο case που εμένα μου ξέφυγε.

**Comment by konstantinosraptis91** [comment]
Θυμάμαι υπήρχε κάποιο ticket που είχε ζητηθεί μια αλλαγή εκεί πέρα. Μπορώ να το βρω από τα commits.

**Comment by konstantinosraptis91** [comment]
https://github.com/UPRC-Interop/espd-vcd-system/commit/2989a631e8bce186520ab192ac434314687ae3e6

https://github.com/UPRC-Interop/espd-vcd-system/commit/b2893ee20990fa97f7dc7632d33128ceb0dea638

https://github.com/UPRC-Interop/espd-vcd-system/commit/bddc490bca7b5596450dae43c60c024398513c7f

**Comment by charis-ant** [comment]
@MariaSpr 

**Διαφορές μεταξύ παραγωγικού και stage**

1. Στο Παραγωγικό στα κριτήρια αποκλεισμού το Γ έχει όλα τα κριτήρια preselected ενώ στο stage στα κριτήρια αποκλεισμού στο Γ τα τρία πρώτα κριτήρια φαίνεται να είναι mandatory.
![image](https://github.com/user-attachments/assets/cb9043d8-09ad-4698-92fe-4a41989c05a0) 
![image](https://github.com/user-attachments/assets/c6d22e85-16bc-4b49-b9b1-e0bb512b7a67)

2. Στο παραγωγικό στο Μέρος V το κριτήριο που αφορά το Reduction of candidates είναι preselected ενώ στο stage δεν είναι επιλεγμένο.
![image](https://github.com/user-attachments/assets/f3c471a8-d011-418a-8af4-b03e15419b4e)
![image](https://github.com/user-attachments/assets/c7662caf-d330-4336-9c24-9a39a272beef)

3. (Minor διαφορά) Στα πεδία που αφορούν την επιλογή χώρας, στο παραγωγικό η λίστα των χωρών είναι στα αγγλικά ενώ στο stage η λίστα των χωρών είναι στα ελληνικά.
![image](https://github.com/user-attachments/assets/c6e0f3e5-ffa1-43ad-8817-f635a2172a82)
![image](https://github.com/user-attachments/assets/d644c8ec-d88a-4ac2-a306-412b6797d62f)

**Comment by MariaSpr** [comment]
@charis-ant σύμφωνα με το commits που έχει βάλει πάνω ο Κωστής, τα 1 και 2 μας τα είχαν ζητήσει.

Σχετικά με το 3. Μας είχαν ζητήσει ελληνικές μεταφράσεις στις codelist οπότε σωστά είναι στο stage

**Comment by MariaSpr** [comment]
Όλα όσα βρήκαμε φαίνεται να μας τα έχουν ζητήσει. Φαίνεται να μην υπάρχει πρόβλημα. Καλό όμως που έχουμε το history.
Κλείνω το issue.
