### ISSUE TITLE
EO registered in a PQS wrong text

### ISSUE THREAD

**Issue by MariaSpr** [UPRC-Interop/espd-vcd-system#4]
Αριστερά το prod pdf
δεξιά το νέο

Λάθη στα λεκτικά:

1. 	Διαφορές στο "Αναφέρετε τα δικαιολογητικά στα οποία βασίζεται η εγγραφή…"
2. 	Ένα ολόκληρο requirementGroup φαίνεται να είναι άκυρο τελείως και να μην έχει σχέση με το συγκεκριμένο κριτήριο

![image](https://github.com/user-attachments/assets/284fe810-feb5-444f-aca4-d099a02ab092)

**Comment by MariaSpr** [comment]
Επιλέον κάτι που παρατήρησα και στο κανονικό παραγωγικό PDF
υπάρχει αυτό εδώ στο παραγωγικό UI αλλά δεν εμφανίζεται πουθενά

![image](https://github.com/user-attachments/assets/5a2fdc95-5c3e-4a63-b757-3f280add4e0c)

**Comment by charis-ant** [comment]
Fixed διαφορές στο "Αναφέρετε τα δικαιολογητικά στα οποία βασίζεται η εγγραφή…" and the random requirement group description. Multiple errors in criteria descriptions and random rendered values might come from codelists/src/main/resources/propertykey.conf

**Comment by charis-ant** [comment]
Somehow no key is rendered for the specific requirement ("Η εγγραφή ή η πιστοποίηση καλύπτει όλα τα απαραίτητα κριτήρια επιλογής"). Two req values are accessed.
![image](https://github.com/user-attachments/assets/d7c6e261-892b-427d-b2c7-142c4c5c8336)

**Comment by MariaSpr** [comment]
Fixed
Note: QA done on branch pdf-issues commit hash 8b23ef0a
