### ISSUE TITLE
Indication of lots text not rendered

### ISSUE THREAD

**Issue by MariaSpr** [UPRC-Interop/espd-vcd-system#5]
Λείπει τελείως το text σχετικά με τα τμήματα για τα οποία κάνει apply ο Εο

![image](https://github.com/user-attachments/assets/dc20d515-51ae-473f-ad49-1e394b2c656c)

**Comment by charis-ant** [comment]
The correct section is now rendered but the label "**Απάντηση:**" is missing
![image](https://github.com/user-attachments/assets/250992e6-a940-49ad-a934-a4ec379e185f)

**Comment by MariaSpr** [comment]
Fixed.
Note: QA done on branch pdf-issues commit hash 8b23ef0a



> The correct section is now rendered but the label "**Απάντηση:**" is missing ![image](https://private-user-images.githubusercontent.com/72884066/358891585-250992e6-a940-49ad-a934-a4ec379e185f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTE0MTEsIm5iZiI6MTcyNDQxMTExMSwicGF0aCI6Ii83Mjg4NDA2Ni8zNTg4OTE1ODUtMjUwOTkyZTYtYTk0MC00OWFkLWE5MzQtYTRlYzM3OWUxODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDExMDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZTNkZjg2ZjFmNjUwNGFmZWE1ZTc3YTM2ZjBmM2U5ZDRhMjJiMTNhNjA5MGI0NjZhNWY4NDA2MjFhYTlmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Gzo2bT8Xrn5AH0GPBStYsQN1piwPYiAldl8u1fUTCg)

I see the "Απάντηση". It is fixed now...
