### ISSUE TITLE
Missing criteria names

### ISSUE THREAD

**Issue by MariaSpr** [UPRC-Interop/espd-vcd-system#7]
Λείπουν τα ονόματα των παρακάτω κριτηρίων:

1. " Συμμετοχή σε εγκληματική οργάνωση"
2. "Τρομοκρατικά εγκλήματα ή εγκλήματα συνδεόμενα με τρομοκρατικές δραστηριότητες"
3. "Νομιμοποίηση εσόδων από παράνομες δραστηριότητες ή χρηματοδότηση της τρομοκρατίας "
4. "Παιδική εργασία και άλλες μορφές εμπορίας ανθρώπων "
5. "Καταβολή εισφορών κοινωνικής ασφάλισης"
6. "Ψευδείς δηλώσεις, απόκρυψη πληροφοριών, ανικανότητα υποβολής δικαιολογητικών, απόκτηση εμπιστευτικών πληροφοριών "
7. "Ασφαλιστική κάλυψη επαγγελματικών κινδύνων "
8. "Άλλες οικονομικές ή χρηματοοικονομικές απαιτήσεις "
9. "Τεχνικό προσωπικό ή τεχνικές υπηρεσίες για τον έλεγχο της ποιότητας "
10. "Τεχνικός εξοπλισμός και μέτρα για την εξασφάλιση της ποιότητας "
11. "Τίτλοι σπουδών και επαγγελματικών προσόντων "
12. "Μέτρα περιβαλλοντικής διαχείρισης "
13. "Μηχανήματα, εγκαταστάσεις και τεχνικός εξοπλισμός "
14. "Αποδοχή ελέγχων "

Παράδειγμα:

![image](https://github.com/user-attachments/assets/227f4834-9a76-45f4-835f-1a71938e2170)

**Comment by charis-ant** [comment]
Still missing: 
5) "Καταβολή εισφορών κοινωνικής ασφάλισης"
6) "Ψευδείς δηλώσεις, απόκρυψη πληροφοριών, ανικανότητα υποβολής δικαιολογητικών, απόκτηση εμπιστευτικών πληροφοριών "

**Comment by MariaSpr** [comment]
Checked everything
Note: QA done on branch pdf-issues commit hash 8b23ef0a
