### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by MariaSpr** [UPRC-Interop/espd-vcd-system#8]
Η μορφοποίηση των ημερομηνιών είναι λάθος:

Παραγωγικό: 02.01.2017
New PDF: 2017-01-02

![image](https://github.com/user-attachments/assets/06bc7906-c2f1-4a8f-aa91-5bac178c7b94)

**Comment by charis-ant** [comment]
The date format in current production is: dd.MM.yyyy

**Comment by MariaSpr** [comment]
Fixed
Note: QA done on branch pdf-issues commit hash 8b23ef0a

**Comment by MariaSpr** [comment]
@charis-ant 

In the following criterion the date format is still misaligned.
Look at criteria in section "Γ: Τεχνική και επαγγελματική ικανότητα"
![image](https://github.com/user-attachments/assets/0b0b17a0-1cd9-4794-84ea-162abee4149f)

**Comment by MariaSpr** [comment]
Fixed
Note: QA done on branch pdf-styled-without-issues commit hash 8dd8dcd9
